// Shared types for the exam practice app.
// All persisted shapes (anything stored in localStorage or in question JSON files)
// are defined here.

export type Difficulty = 'easy' | 'medium' | 'hard'

export type MasteryState = 'unassessed' | 'weak' | 'in_progress' | 'mastered'

export type FeedbackMode = 'immediate' | 'end_of_set'

export type SetSize = 30 | 60 | 100

export type Screen =
  | 'profile_select'
  | 'set_config'
  | 'active_set'
  | 'set_summary'
  | 'dashboard'
  | 'settings'

// === Question bank (matches JSON schema on disk) ===

export type QuestionOption = {
  text: string
  image: string | null
}

export type Question = {
  id: string
  text: string
  image: string | null
  options: QuestionOption[]
  correct: number // zero-based index into options
  difficulty: Difficulty
  expected_time_sec: number
  score: number
  explanation: string
}

// === Manifest (auto-generated by build-manifest script) ===

export type TopicMeta = {
  topicId: string // stable id, e.g. "science/physics/light"
  subject: string
  topic: string
  subtopic: string
  filePath: string // path used by questionLoader to fetch the file
  questionCount: number
}

export type Manifest = {
  topics: TopicMeta[]
}

// === Per-set results & accumulated progress ===

export type QuestionResult = {
  questionId: string
  topicId: string
  // Optional so existing fixtures can omit it; SessionScreen populates it
  // for the SummaryScreen drilldown. `undefined` is equivalent to 'skipped'.
  selectedAnswer?: number | 'skipped'
  correct: boolean
  skipped: boolean
  elapsedSec: number
  expectedSec: number
}

export type TopicProgress = {
  topicId: string
  masteryState: MasteryState
  lastSetAccuracy: number // 0..1
  lastSetTimeRatio: number // 1.0 = exactly the expected time
  incorrectQuestionIds: string[]
  seenQuestionIds: string[]
}

export type TopicStateChange = {
  topicId: string
  previousState: MasteryState
  newState: MasteryState
}

export type SetRecord = {
  setNumber: number
  date: string // ISO 8601 timestamp
  size: SetSize
  feedbackMode: FeedbackMode
  results: QuestionResult[]
  topicStateChanges: TopicStateChange[]
}

// Compact form of SetRecord, used to preserve dashboard-relevant signal
// (accuracy + topic state changes) for older sets after the full
// per-question results have been rolled off to keep localStorage bounded.
export type SetRecordSummary = {
  setNumber: number
  date: string
  size: SetSize
  feedbackMode: FeedbackMode
  accuracy: number // 0..1
  correctCount: number
  totalCount: number
  topicStateChanges: TopicStateChange[]
}

// === Profile & persistence ===

export type Profile = {
  name: string
  createdAt: string // ISO 8601
}

export type ProfileProgress = {
  profile: Profile
  topicProgress: TopicProgress[]
  setHistory: SetRecord[]
  // Older sets, summarized. Older entries first. Optional so existing exports
  // (and freshly created profiles whose history hasn't yet exceeded the cap)
  // round-trip unchanged.
  setHistorySummary?: SetRecordSummary[]
  darkMode: boolean
  streak: number
  lastSetDate: string | null // YYYY-MM-DD, used for streak calc
}

// === Set configuration & in-flight runtime state ===

export type SetConfig = {
  size: SetSize
  feedbackMode: FeedbackMode
}

// Runtime state of an in-progress set. Not persisted — converted to
// QuestionResult[] on submit.
export type ActiveSet = {
  questionIds: string[]
  setConfig: SetConfig
  currentIndex: number
  answers: Map<string, number | 'skipped'>
  timings: Map<string, number> // questionId -> elapsed seconds
}
